#!/usr/bin/env bash
# Script which must be sourced to setup the development environment.

# This has to be the first command because BASH_SOURCE[0] gets changed.
SCRIPT=${BASH_SOURCE[0]:-$0}

[[ "${BASH_SOURCE[0]}" == "$0" ]] \
    && echo "This script should not be executed but sourced like:" \
    && echo "    $ source $0" \
    && echo \
    && exit 1

SCRIPT_DIR=$(dirname $(realpath $SCRIPT))
export PS_DEMO_REPO_DIR=$(realpath $SCRIPT_DIR/..)
export LOCAL_ENVPATH=$(realpath $PS_DEMO_REPO_DIR/..)

export LDFLAGS="-L/usr/local/opt/libffi/lib"
export LD_LIBRARY_PATH=/usr/local/lib
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig"

export PATH="$LOCAL_ENVPATH/bin/:$PATH"

export PS1="(jarvis-env) $PS1"


echo "===================================================================="
echo '                   _         _______      _______  _____            '
echo '                  | |  /\   |  __ \ \    / /_   _|/ ____|           '
echo '                  | | /  \  | |__) \ \  / /  | | | (___             '
echo '              _   | |/ /\ \ |  _  / \ \/ /   | |  \___ \            '
echo '             | |__| / ____ \| | \ \  \  /   _| |_ ____) |           '
echo '              \____/_/    \_\_|  \_\  \/   |_____|_____/            '
echo "===================================================================="
echo "PS_DEMO_REPO_DIR = ${PS_DEMO_REPO_DIR}"
echo "LOCAL_ENVPATH = ${LOCAL_ENVPATH}"
echo "LDFLAGS = ${LDFLAGS}"
echo "LD_LIBRARY_PATH = ${LD_LIBRARY_PATH}"
echo "PKG_CONFIG_PATH = ${PKG_CONFIG_PATH}"
